package(default_visibility = ["//visibility:public"])

exports_files([
    "c_cpp_properties.json",
    "extensions.json",
    "launch.json",
    "tasks.json",
])

filegroup(
    name = "sources",
    srcs = glob(["*.json"]) + ["BUILD"],
)
