module(
    name = "tetro_toolchain",
    version = "0.1.0",
)

bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_pkg", version = "1.3.0")

emscripten_sysroot = use_repo_rule("//:wasm.bzl", "emscripten_sysroot")

emscripten_sysroot(name = "emscripten_sysroot")

windows_sdk = use_repo_rule("//:windows.bzl", "windows_sdk")

windows_sdk(name = "windows_sdk")
